# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kv7AW9WmbuUmfwe4FJjpOo8xd6hgchso
"""

!pip install diffusers transformers accelerate safetensors pillow

import torch

from diffusers import StableDiffusionPipeline

from PIL import Image, ImageDraw, ImageFont, ImageEnhance

model_id = "SG161222/Realistic_Vision_V5.1_noVAE"

!pip install -q diffusers transformers accelerate safetensors gradio pillow

from huggingface_hub import login

from google.colab import userdata

from google.colab import userdata
from huggingface_hub import login

login(token=userdata.get('newpankaj'))

login(token=userdata.get('newpankaj'))

prompt = """
A premium fashion poster of a beautiful Indian woman wearing a royal red silk saree,
gold jewelry, elegant pose, luxury studio background, soft cinematic lighting,
realistic skin texture, detailed fabric, professional photography, 85mm lens,
sharp focus, ultra detailed, high fashion advertisement style
"""

negative_prompt = """
low quality, blurry, bad anatomy, extra fingers, distorted face, bad hands,
text, watermark, logo, overexposed, underexposed, cartoon, deformed
"""

import torch
print(torch.cuda.is_available())

import torch
from diffusers import StableDiffusionPipeline

model_id = "SG161222/Realistic_Vision_V5.1_noVAE"
pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)
pipe = pipe.to("cuda")

pipe.enable_attention_slicing()

pipe.enable_vae_slicing()

image = pipe(
    "Indian luxury fashion advertisement poster, beautiful Indian woman wearing red saree, gold jewelry, professional studio lighting",
    height=512,
    width=512,
    num_inference_steps=20
).images[0]

image = pipe(
    """Ultra realistic Indian luxury fashion advertisement poster,
beautiful Indian female model,
symmetrical face,
perfect eyes,
detailed skin texture,
wearing elegant BLUE saree,
gold jewelry,
professional fashion photography,
studio lighting,
commercial advertising,
sharp focus,
high detail,
premium ethnic fashion campaign,
cinematic lighting
"""
    ,
    height=512,
    width=512,
    num_inference_steps=15,
    guidance_scale=7
).images[0]

negative_prompt = """
ugly face,
deformed eyes,
bad anatomy,
extra fingers,
extra hands,
blurry,
low quality,
cropped face,
duplicate body,
distorted face,
poor lighting,
cartoon,
anime,
3d render
"""

display(image)

# ============================================
# IMPORT LIBRARIES
# ============================================

import torch
import gradio as gr

from PIL import (
    Image,
    ImageDraw,
    ImageFont,
    ImageEnhance
)

from diffusers import (
    StableDiffusionPipeline,
    StableDiffusionImg2ImgPipeline
)

# ============================================
# LOAD MODEL
# ============================================

model_id = "SG161222/Realistic_Vision_V5.1_noVAE"

# ============================================
# TEXT TO IMAGE PIPELINE
# ============================================

txt2img_pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    safety_checker=None
)

# ============================================
# IMG2IMG PIPELINE
# ============================================

img2img_pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    safety_checker=None
)

# ============================================
# MOVE TO GPU
# ============================================

txt2img_pipe = txt2img_pipe.to("cuda")
img2img_pipe = img2img_pipe.to("cuda")

# ============================================
# OPTIMIZATIONS
# ============================================

txt2img_pipe.enable_attention_slicing()
txt2img_pipe.enable_vae_slicing()

img2img_pipe.enable_attention_slicing()
img2img_pipe.enable_vae_slicing()

# ============================================
# FIXED INDIAN STYLE CONSTRAINTS
# ============================================

INDIAN_STYLE = """
Ultra realistic Indian luxury advertisement poster,
beautiful Indian female model,
Indian ethnic fashion,
Indian skin tone,
pink colour,
red colour,
green colour,
black colour,
blue colour,
white colour,
yellow colour,
purple colour,



traditional Indian aesthetics,
professional fashion photography,
commercial advertising,
luxury jewelry,
studio lighting,
cinematic lighting,
sharp focus,
detailed skin texture,
premium marketing campaign,
high fashion editorial,
symmetrical face,
perfect eyes,
highly detailed fabric,
realistic pose
"""

# ============================================
# NEGATIVE PROMPT
# ============================================

NEGATIVE_PROMPT = """
ugly face,
deformed face,
cross eyes,
bad anatomy,
extra fingers,
extra hands,
mutated hands,
duplicate face,
cropped head,
blurry,
low quality,
western style,
anime,
cartoon,
3d render,
plastic skin,
bad teeth,
bad eyes,
fake face,
low resolution,
watermark,
logo,
text
"""

# ============================================
# PROMPT ENHANCEMENT FUNCTION
# ============================================

def enhance_prompt(user_prompt):

    enhanced_prompt = f"""
    {INDIAN_STYLE}

    {user_prompt}

    premium Indian commercial advertisement,
    luxury ethnic fashion campaign,
    elegant pose,
    fashion magazine quality,
    advertisement photography,
    cinematic composition,
    realistic beauty campaign
    """

    return enhanced_prompt

# ============================================
# TEXT TO IMAGE GENERATION
# ============================================

def generate_ad(
    user_prompt,
    title,
    subtitle
):

    final_prompt = enhance_prompt(user_prompt)

    image = txt2img_pipe(
        prompt=final_prompt,
        negative_prompt=NEGATIVE_PROMPT,
        height=768,
        width=512,
        num_inference_steps=30,
        guidance_scale=8
    ).images[0]

    image = ImageEnhance.Sharpness(image).enhance(1.3)
    image = ImageEnhance.Contrast(image).enhance(1.1)
    image = ImageEnhance.Color(image).enhance(1.1)

    draw = ImageDraw.Draw(image);

    # Load default fonts (arial.ttf not consistently available)
    title_font = ImageFont.load_default()
    subtitle_font = ImageFont.load_default()

    # Define image dimensions
    img_width, img_height = image.size

    # Define the approximate area for the text box at the bottom
    text_box_left = 20
    text_box_right = img_width - 20
    text_box_bottom = img_height - 20

    # Calculate title and subtitle dimensions using the loaded fonts
    title_bbox = draw.textbbox((0, 0), title, font=title_font)
    title_width = title_bbox[2] - title_bbox[0]
    title_height = title_bbox[3] - title_bbox[1]

    subtitle_bbox = draw.textbbox((0, 0), subtitle, font=subtitle_font)
    subtitle_width = subtitle_bbox[2] - subtitle_bbox[0]
    subtitle_height = subtitle_bbox[3] - subtitle_bbox[1]

    # Padding and spacing
    vertical_text_padding = 10 # Padding above title and below subtitle
    spacing_between_lines = 5 # Space between title and subtitle

    # Calculate required height for the text content
    total_text_content_height = title_height + spacing_between_lines + subtitle_height

    # Calculate the top of the text box dynamically
    text_box_top = text_box_bottom - total_text_content_height - (2 * vertical_text_padding)

    # Calculate centered X positions
    title_x = text_box_left + (text_box_right - text_box_left - title_width) / 2
    subtitle_x = text_box_left + (text_box_right - text_box_left - subtitle_width) / 2

    # Calculate Y positions for text, starting from the top of the text box
    current_y = text_box_top + vertical_text_padding
    title_y = current_y
    subtitle_y = title_y + title_height + spacing_between_lines

    # Draw the background rectangle
    draw.rectangle(
        (text_box_left, text_box_top, text_box_right, text_box_bottom),
        fill=(0, 0, 0)
    )

    # Draw the text
    draw.text((title_x, title_y), title, font=title_font, fill=(255, 215, 0)) # Gold
    draw.text((subtitle_x, subtitle_y), subtitle, font=subtitle_font, fill=(255, 255, 255)) # White

    return image

# ============================================
# IMAGE TO IMAGE GENERATION
# ============================================

def generate_variation(
    input_image,
    user_prompt,
    title,
    subtitle,
    strength
):
    input_image = input_image.resize((512, 768))
    final_prompt = enhance_prompt(user_prompt)

    image = img2img_pipe(
        image=input_image,
        prompt=final_prompt,
        negative_prompt=NEGATIVE_PROMPT,
        strength=strength,
        num_inference_steps=30,
        guidance_scale=8
    ).images[0]

    image = ImageEnhance.Sharpness(image).enhance(1.3)
    image = ImageEnhance.Contrast(image).enhance(1.1)
    image = ImageEnhance.Color(image).enhance(1.1)

    draw = ImageDraw.Draw(image)

    # Load default fonts (arial.ttf not consistently available)
    title_font = ImageFont.load_default()
    subtitle_font = ImageFont.load_default()

    # Define image dimensions
    img_width, img_height = image.size

    # Define the approximate area for the text box at the bottom
    text_box_left = 20
    text_box_right = img_width - 20
    text_box_bottom = img_height - 20

    # Calculate title and subtitle dimensions using the loaded fonts
    title_bbox = draw.textbbox((0, 0), title, font=title_font)
    title_width = title_bbox[2] - title_bbox[0]
    title_height = title_bbox[3] - title_bbox[1]

    subtitle_bbox = draw.textbbox((0, 0), subtitle, font=subtitle_font)
    subtitle_width = subtitle_bbox[2] - subtitle_bbox[0]
    subtitle_height = subtitle_bbox[3] - subtitle_bbox[1]

    # Padding and spacing
    vertical_text_padding = 10 # Padding above title and below subtitle
    spacing_between_lines = 5 # Space between title and subtitle

    # Calculate required height for the text content
    total_text_content_height = title_height + spacing_between_lines + subtitle_height

    # Calculate the top of the text box dynamically
    text_box_top = text_box_bottom - total_text_content_height - (2 * vertical_text_padding)

    # Calculate centered X positions
    title_x = text_box_left + (text_box_right - text_box_left - title_width) / 2
    subtitle_x = text_box_left + (text_box_right - text_box_left - subtitle_width) / 2

    # Calculate Y positions for text, starting from the top of the text box
    current_y = text_box_top + vertical_text_padding
    title_y = current_y
    subtitle_y = title_y + title_height + spacing_between_lines

    # Draw the background rectangle
    draw.rectangle(
        (text_box_left, text_box_top, text_box_right, text_box_bottom),
        fill=(0, 0, 0)
    )

    # Draw the text
    draw.text((title_x, title_y), title, font=title_font, fill=(255, 215, 0)) # Gold
    draw.text((subtitle_x, subtitle_y), subtitle, font=subtitle_font, fill=(255, 255, 255)) # White

    return image

# ============================================
# ENHANCE FINAL IMAGE
# ============================================

image = ImageEnhance.Sharpness(image).enhance(1.3)
image = ImageEnhance.Contrast(image).enhance(1.1)
image = ImageEnhance.Color(image).enhance(1.1)

# ============================================
# ADD POSTER TEXT
# ============================================

draw = ImageDraw.Draw(image)

import gradio as gr

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# Indian Luxury Fashion Ad Generator")

    with gr.Tab("Text to Image (Generate New Ad)"):
        with gr.Row():
            with gr.Column():
                user_prompt_t2i = gr.Textbox(
                    label="Ad Description",
                    placeholder="Describe your ad here...",
                    lines=3
                )
                ad_title_t2i = gr.Textbox(
                    label="Ad Title",
                    placeholder="Enter a catchy title"
                )
                ad_subtitle_t2i = gr.Textbox(
                    label="Ad Subtitle",
                    placeholder="Enter a compelling subtitle"
                )
                generate_btn_t2i = gr.Button("Generate Ad")
            with gr.Column():
                output_image_t2i = gr.Image(
                    label="Generated Ad",
                    type="pil"
                )

    with gr.Tab("Image to Image (Generate Variation)"):
        with gr.Row():
            with gr.Column():
                input_image_i2i = gr.Image(
                    label="Upload Base Image",
                    type="pil"
                )
                user_prompt_i2i = gr.Textbox(
                    label="Ad Description (for variation)",
                    placeholder="Describe desired changes or style...",
                    lines=3
                )
                ad_title_i2i = gr.Textbox(
                    label="Ad Title (for variation)",
                    placeholder="Enter a catchy title"
                )
                ad_subtitle_i2i = gr.Textbox(
                    label="Ad Subtitle (for variation)",
                    placeholder="Enter a compelling subtitle"
                )
                strength_slider_i2i = gr.Slider(
                    minimum=0.0,
                    maximum=1.0,
                    value=0.75,
                    label="Strength (for image-to-image)"
                )
                generate_btn_i2i = gr.Button("Generate Variation")
            with gr.Column():
                output_image_i2i = gr.Image(
                    label="Generated Ad Variation",
                    type="pil"
                )

    # Connect event listeners
    generate_btn_t2i.click(
        generate_ad,
        inputs=[user_prompt_t2i, ad_title_t2i, ad_subtitle_t2i],
        outputs=output_image_t2i
    )
    generate_btn_i2i.click(
        generate_variation,
        inputs=[
            input_image_i2i,
            user_prompt_i2i,
            ad_title_i2i,
            ad_subtitle_i2i,
            strength_slider_i2i
        ],
        outputs=output_image_i2i
    )

demo.launch(
    share=True,
    debug=True
)